# 【dev】 环境
server:
  port: 2323

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoConnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root